server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
instance:
hostname: localhost
serviceUrl:
defaultZone: http://eureka.instance.hostname:{eureka.instance.hostname}:eureka.instance.hostname:{server.port}/eureka/
